# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=1)),
                ('group_as_string', models.CharField(max_length=4)),
                ('teacher_as_string', models.CharField(max_length=80)),
                ('gt_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', models.CharField(max_length=50)),
            ],
        ),
    ]
