# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmschedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pref',
            old_name='teacher_as_string',
            new_name='gt_as_string',
        ),
        migrations.RemoveField(
            model_name='pref',
            name='group_as_string',
        ),
    ]
